# Generated by Django 5.2.6 on 2025-09-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Введите телеграм chat_id",
                max_length=50,
                null=True,
                verbose_name="Телеграм chat_id",
            ),
        ),
    ]
