# Generated by Django 5.2.6 on 2025-09-15 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название привычки",
                        max_length=100,
                        verbose_name="Название привычки",
                    ),
                ),
                (
                    "action",
                    models.TextField(
                        blank=True,
                        help_text="Укажите действие, которое представляет собой привычка",
                        null=True,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место выполнения привычки",
                        max_length=255,
                        null=True,
                        verbose_name="Место",
                    ),
                ),
                (
                    "lead_time",
                    models.TimeField(
                        blank=True,
                        help_text="Укажите в какое время планируется выполнять привычку",
                        null=True,
                        verbose_name="Время",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Выберите через сколько дней будите выполнять полезную привычку (1-7)",
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, что привычка является приятной (вознаграждаемой)",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение за выполнение привычки",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_for_task",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Укажите время на выполнения полезной привычки",
                        null=True,
                        verbose_name="Время на выполнение в секундах",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Публичная привычка, доступная другим пользователям",
                        verbose_name="Публиковать привычку",
                    ),
                ),
                (
                    "associated_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите связанную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["user", "name"],
            },
        ),
    ]
