# Generated by Django 5.2.6 on 2025-09-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="date_last_execution",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Дата последнего выполнения полезной привычки",
            ),
        ),
    ]
