# Generated by Django 5.2.6 on 2025-09-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_habit_date_last_execution"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ["owner", "name"],
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
        migrations.RenameField(
            model_name="habit",
            old_name="user",
            new_name="owner",
        ),
    ]
